version: '3'
services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sampledb
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmintweb:
    image: dpage/pgadmin4
    container_name: pgadminwebtbot
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5051:80'
    depends_on:
      - db
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    ports:
      - '5000:5000'
    volumes:
      - ./:/app
    depends_on:
      - db
volumes:
  postgres_data:
