name: Card Games Docker image
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build . -t nahi002/cardgames:latest

      - name: Push image to Docker Hub
        run: |
          docker login -u nahi002 -p ${{ secrets.CARD_GAMES_TOKEN }}
          docker push nahi002/cardgames:latest
